### ISSUE TITLE
Bug: getS3EndpointForRegion is not defined in serverless 1.27

### ISSUE THREAD

**Issue by egut** [trek10inc/serverless-cloudformation-parameters#3]
When using serverless-cloudformation-parameter-setter with serverless 1.27 I get the following error:

`getS3EndpointForRegion is not defined`

it do not appear in serverless 1.26 if I try with a project that do not have serverless-cloudformation-parameter-setter I don't get this issue.

Full debug log:

```
$ SLS_DEBUG=* sls deploy -v --force
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command graph
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
 
  Reference Error ----------------------------------------
 
  getS3EndpointForRegion is not defined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
ReferenceError: getS3EndpointForRegion is not defined
    at AwsDeploy.eval [as update] (eval at ServerlessCloudFormationParameterSetter (/home/CORPUSERS/23061097/src/mobiam/mobiam-aws/api/node_modules/serverless-cloudformation-parameter-setter/index.js:15:26), <anonymous>:4:24)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:112:12)
From previous event:
    at AwsDeploy.updateStack (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:106:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:135:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:131:10)
    at BbPromise.reduce (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/home/CORPUSERS/23061097/.nvm/versions/v8.10.0/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.27.2
 
```

**Comment by jhecking** [comment]
Running into this error as well with:
* serverless@1.37.1
* serverless-cloudformation-parameter-setter@0.0.1

Is there any work-around possible?

**Comment by chaitanya11** [comment]
With sls@1.38.0 version also

**Comment by toryas** [comment]
> Running into this error as well with:
> 
> * serverless@1.37.1
> * serverless-cloudformation-parameter-setter@0.0.1
> 
> Is there any work-around possible?


I created a plugin to use parameters as I did not see support for this plugin. I know it's late but maybe it will work for you.

[serverless-cf-parameters](https://www.npmjs.com/package/serverless-cf-parameters)

**Comment by mfernand0** [comment]
hello there, is this working already? can't make it work even with the latest version 2.11, any fix?

**Comment by toryas** [comment]
> hello there, is this working already? can't make it work even with the latest version 2.11, any fix?
I make an alternative lib try this https://github.com/toryas/serverless-cf-parameters
